[tool.ruff]
# Fast, strict-enough defaults. Keep it lean.
line-length = 100
indent-width = 4
# backend/pyproject.toml

[tool.ruff]
extend-exclude = [
  ".venv",
  "**/__pycache__",
  # Exclude legacy types and mocks folders from linting noise for now
  "types/**",
  "types_old/**",
]
# Enable common rule sets: Pyflakes (F), pycodestyle (E/W). Omit I/N for now.
select = ["F", "E", "W"]

[tool.ruff.per-file-ignores]
# Belt-and-braces: if files in these dirs are picked up, ignore common noise
"**/types/**/*.py" = ["F401", "F405", "E", "W"]
"**/types_old/**/*.py" = ["F401", "F405", "E", "W"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
