import { Card, CardRarity } from '../types/game.types';

export const MOCK_CARDS: Card[] = [
  {
    id: 1,
    name: 'Cyber Soldier',
    type: 'character',
    cost: 3,
    attack: 2,
    health: 3,
    rarity: 'common' as CardRarity,
    description: 'Basic infantry unit with enhanced targeting systems',
    abilities: ['First Strike'],
  },
  {
    id: 2,
    name: 'Neural Hack',
    type: 'action',
    cost: 2,
    rarity: 'rare' as CardRarity,
    description: 'Disable target enemy unit for one turn',
    abilities: ['Instant', 'Disable'],
    isInstant: true,
    targetType: 'unit',
    effect: () => {},
  },
  {
    id: 3,
    name: 'Plasma Cannon',
    type: 'character',
    cost: 5,
    attack: 4,
    health: 2,
    rarity: 'epic' as CardRarity,
    description: 'Heavy weapons platform with area damage capabilities',
    abilities: ['Area Damage', 'Range 2'],
  },
  {
    id: 4,
    name: 'Data Stream',
    type: 'action',
    cost: 1,
    rarity: 'common' as CardRarity,
    description: 'Access tactical networks • Draw 2 cards from your deck',
    abilities: ['Draw', 'Instant'],
    isInstant: true,
    effect: () => {},
  },
  {
    id: 5,
    name: 'Quantum Guardian',
    type: 'character',
    cost: 7,
    attack: 3,
    health: 8,
    rarity: 'legendary' as CardRarity,
    description: 'Advanced defense unit with damage mitigation',
    abilities: ['Shield', 'Taunt'],
  },
];
