import { Card, CardRarity, CardType } from '../types/game.types';

export const MOCK_CARDS: Card[] = [
  {
    id: 1,
    name: 'Cyber Soldier',
    type: CardType.Character,
    cost: 3,
    attack: 2,
    health: 3,
    rarity: CardRarity.Common,
    description: 'Basic infantry unit with enhanced targeting systems',
    abilities: ['First Strike'],
  },
  {
    id: 2,
    name: 'Neural Hack',
    type: CardType.Action,
    cost: 2,
    rarity: CardRarity.Rare,
    description: 'Disable target enemy unit for one turn',
    abilities: ['Instant', 'Disable'],
    isInstant: true,
    targetType: 'unit',
    effect: () => {},
  },
  {
    id: 3,
    name: 'Plasma Cannon',
    type: CardType.Character,
    cost: 5,
    attack: 4,
    health: 2,
    rarity: CardRarity.Epic,
    description: 'Heavy weapons platform with area damage capabilities',
    abilities: ['Area Damage', 'Range 2'],
  },
  {
    id: 4,
    name: 'Data Stream',
    type: CardType.Action,
    cost: 1,
    rarity: CardRarity.Common,
    description: 'Access tactical networks • Draw 2 cards from your deck',
    abilities: ['Draw', 'Instant'],
    isInstant: true,
    effect: () => {},
  },
  {
    id: 5,
    name: 'Quantum Guardian',
    type: CardType.Character,
    cost: 7,
    attack: 3,
    health: 8,
    rarity: CardRarity.Legendary,
    description: 'Advanced defense unit with damage mitigation',
    abilities: ['Shield', 'Taunt'],
  },
];
